wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685610040.474886
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 71
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 83
      3:
      - 7
      - 23
      4: 3.8.10
      5: 0.15.3
      6: 4.29.2
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
